#!/bin/bash

set -e

DIR=$( cd "$( dirname "$0" )" && pwd )
DOTFILES=$DIR/dotfiles

PATH="/opt/homebrew/bin:$PATH"

linked() {
    ln -shf "$DOTFILES/$1" "$HOME/$1"
}

dotfiles() {
    echo "Linking all dotfiles to home directory"

    linked ".irbrc"
    linked ".gitconfig"
    linked ".tmux.conf"
    linked ".tmuxinator"
    linked ".emacs.d"
    linked ".gemrc"

    linked "bin"

    mkdir -p ~/.config
    linked ".config/fish"

    mkdir -p ~/Library/KeyBindings
    linked "Library/KeyBindings/DefaultKeyBinding.dict"
}

updateBrew() {
    set +e

    which brew
    if [ $? -ne 0 ] ; then
        echo Installing Homebrew
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    echo Updating Homebrew
    brew update
    brew upgrade
}

brewBundle() {
    echo Installing packages from Brewfile
    brew bundle --verbose
}

iTermConfig() {
    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DIR/dotfiles/iterm"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

setFishShell() {
    echo Setting shell to fish
    # Add fish to shells
    grep fish /etc/shells
    if [ $? -ne 0 ]; then
        sudo sh -c "echo /opt/homebrew/bin/fish >> /etc/shells"
        # Change shell to fish
        chsh -s /opt/homebrew/bin/fish
    fi
}

install() {
    asdf plugin add ruby
    asdf plugin add nodejs
    asdf plugin add python
    asdf plugin add golang

    asdf install ruby latest
    asdf install nodejs latest
    asdf install python latest
    asdf install golang latest

    asdf global ruby latest
    asdf global nodejs latest
    asdf global python latest
    asdf global golang latest

    PATH="$HOME/.asdf/shims:$PATH"
    gem install -N tmuxinator

    go install github.com/vroy/git-gb
    go install mvdan.cc/gofumpt@latest

    pip3 install requests
}

osxDefaults() {
    echo Mac OS Defaults
    ./os_x_defaults.sh
}

dotfiles
updateBrew
brewBundle
install
iTermConfig
setFishShell
osxDefaults
