#!/bin/bash

set -e

DIR=$( cd "$( dirname "$0" )" && pwd )
DOTFILES=$DIR/dotfiles

linked() {
    ln -shf "$DOTFILES/$1" "$HOME/$1"
}

dotfiles() {
    echo "Linking all dotfiles to home directory"

    linked ".irbrc"
    linked ".gitconfig"
    linked ".tmux.conf"
    linked ".tmuxinator"
    linked ".emacs.d"
    linked ".gemrc"

    linked "bin"

    mkdir -p ~/.config
    linked ".config/fish"

    mkdir -p ~/Library/Application\ Support/Code/User
    linked "Library/Application Support/Code/User/settings.json"
    linked "Library/Application Support/Code/User/keybindings.json"

    mkdir -p ~/Library/KeyBindings
    linked "Library/KeyBindings/DefaultKeyBinding.dict"
}

updateBrew() {
    which brew
    if [ $? -ne 0 ] ; then
        echo Installing Homebrew
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    echo Updating Homebrew
    brew update
    brew upgrade

    echo "Creating /usr/local/Frameworks"
    sudo mkdir -p /usr/local/Frameworks
    sudo chown $(whoami):admin /usr/local/Frameworks
}

brewBundle() {
    echo Installing packages from Brewfile
    brew bundle --verbose
}

iTermConfig() {
    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DIR/dotfiles/iterm"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

setFishShell() {
    echo Setting shell to fish
    # Add fish to shells
    grep fish /etc/shells
    if [ $? -ne 0 ]; then
        sudo sh -c "echo /usr/local/bin/fish >> /etc/shells"
        # Change shell to fish
        chsh -s /usr/local/bin/fish
    fi
}

installGems() {
    gem install tmuxinator
    gem install octokit
}

installOthers() {
    go get github.com/vroy/git-gb
}

osxDefaults() {
    echo Mac OS Defaults
    ./os_x_defaults.sh
}

codeExtensions() {
    echo Installing VS Code Extensions

    # Editor
    code --install-extension christian-kohler.path-intellisense
    code --install-extension christian-kohler.npm-intellisense
    code --install-extension hiro-sun.vscode-emacs
    code --install-extension slevesque.vscode-multiclip
    code --install-extension streetsidesoftware.code-spell-checker


    # Languages
    code --install-extension lukehoban.Go
    code --install-extension ms-python.python
    code --install-extension PeterJausovec.vscode-docker
    code --install-extension rebornix.ruby
    code --install-extension robinbentley.sass-indented

    # VueJS and JavaScript
    code --install-extension dbaeumer.vscode-eslint
    code --install-extension octref.vetur
    code --install-extension dariofuzinato.vue-peek
}

configurePython() {
    echo "Updating pip"
    pip3 install --upgrade pip setuptools wheel

    pip3 install requests
}

dotfiles
updateBrew
brewBundle
configurePython
installGems
installOthers
iTermConfig
setFishShell
osxDefaults
codeExtensions
