;; Self
(source gnu)
(source melpa)
(depends-on "cask")

;; Project
(depends-on "projectile")
(depends-on "ag")
(depends-on "grizzl")
(depends-on "fiplr")

;; interactive buffers
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "ido-completing-read+")
(depends-on "ido-vertical-mode")

(depends-on "yasnippet")

;; Modes
(depends-on "rhtml-mode")
(depends-on "yaml-mode")
(depends-on "scss-mode")
(depends-on "sass-mode")
(depends-on "nginx-mode") ;; https://github.com/ajc/nginx-mode
(depends-on "markdown-mode")
(depends-on "dockerfile-mode")
(depends-on "groovy-mode")
(depends-on "cask-mode")
(depends-on "jinja2-mode")
(depends-on "web-mode")
(depends-on "plantuml-mode")
(depends-on "terraform-mode")

;; Themes
(depends-on "zenburn-theme")

;; Others
(depends-on "diminish")
(depends-on "exec-path-from-shell")

;; https://github.com/chrisdone/god-mode
(depends-on "god-mode")

(depends-on "auto-complete")

;; External dependencies:
;; go get -u github.com/rogpeppe/godef
;; go get -u github.com/kisielk/errcheck
;; go get -u github.com/nsf/gocode
;; go get -u golang.org/x/tools/cmd/goimports
(depends-on "go-mode")
(depends-on "go-errcheck")
(depends-on "go-autocomplete")

(depends-on "flycheck")
(depends-on "zoom-window")
